#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Curtis Galloway
# SPDX-License-Identifier: Apache-2.0
"""Rewrite the stable pins in a Homebrew formula, in place.

The pure, no-network half of scripts/repin.sh: given a formula file, a new
version, and one (filename-suffix, url, sha256) triple per release asset, it
rewrites the matching `url`/`sha256` line pairs and the top-level `version`
line. Kept separate from repin.sh (which does the `gh release download` and
sidecar verification) so the rewrite itself can be unit-tested against a
fixture formula with no network access and no `gh` invocation
(scripts/test_repin_rewrite.py).

Matching is by filename suffix, not by line position or block nesting, so it
finds a `url` line wherever it lives in the file and is indifferent to how
many times a given asset is pinned (Formula/paniolo.rb pins the macOS
tarball twice, once under on_arm and once under on_intel, because both
architectures share one universal binary). It refuses to touch anything
inside a `head do ... end` block — the --HEAD spec builds from a git
checkout and must keep its own `url`, not a release tarball's.

It also owns the formula's `bottle do ... end` block. Given
`--bottle-root-url` and one `--bottle TAG SHA256` per bottle the release
published, it writes the block (replacing an existing one, or inserting one
after the head block); given none, it removes any existing block, so
re-pinning to a release that predates bottles never leaves a stale one
behind. The block and the comment above it are generated whole, which is
what lets the removal be exact.
"""

import argparse
import re
import sys

VERSION_RE = re.compile(r'^(?P<indent>\s*)version "(?P<value>[^"]*)"\s*$')
URL_RE = re.compile(r'^(?P<indent>\s*)url "(?P<value>[^"]*)"\s*$')
SHA256_RE = re.compile(r'^(?P<indent>\s*)sha256 "(?P<value>[0-9a-fA-F]{64})"\s*$')
HEAD_START_RE = re.compile(r"^(?P<indent>\s*)head do\s*$")
BOTTLE_START_RE = re.compile(r"^(?P<indent>\s*)bottle do\s*$")
LICENSE_RE = re.compile(r'^(?P<indent>\s*)license "[^"]*"\s*$')
COMMENT_RE = re.compile(r"^(?P<indent>\s*)#")
SHA256_HEX_RE = re.compile(r"^[0-9a-f]{64}$")
BOTTLE_TAG_RE = re.compile(r"^[a-z][a-z0-9_]*$")

# The comment written above every generated bottle block. It is part of the
# block for removal purposes: rewrite_bottles() strips the contiguous
# comment lines directly above `bottle do` along with the block itself.
BOTTLE_COMMENT = [
    "# Bottles: the release's own binaries wrapped in keg layout by paniolo's",
    '# release workflow ("Build Homebrew bottle" steps), so `brew install`',
    "# pours them. A pour skips Homebrew's build-from-source preflight, which",
    "# refuses outright on a macOS newer than its Xcode table (paniolo #225)",
    "# even though this formula never compiles anything. `all` serves every",
    "# macOS version and arch because the binaries are universal; the Linux",
    "# tags are exact because Homebrew 7 matches a bottle by its exact tag or",
    "# `all`, never an older OS's. Generated by scripts/repin_rewrite.py on",
    "# each bump — edit that script, not this block.",
]


def parse_args(argv):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("formula", help="path to the formula file to rewrite in place")
    parser.add_argument("--version", required=True, help='new "X.Y.Z" to write to the version line')
    parser.add_argument(
        "--asset",
        action="append",
        nargs=3,
        metavar=("SUFFIX", "URL", "SHA256"),
        default=[],
        help="repeatable: a release asset's filename suffix (e.g. macos-universal.tar.gz), "
        "its new url, and its new sha256",
    )
    parser.add_argument(
        "--bottle-root-url",
        help="root_url for the bottle block: the release's download directory, "
        "where Homebrew appends <name>-<version>.<tag>.bottle.tar.gz",
    )
    parser.add_argument(
        "--bottle",
        action="append",
        nargs=2,
        metavar=("TAG", "SHA256"),
        default=[],
        help="repeatable: a bottle tag (all, arm64_linux, x86_64_linux, ...) and the "
        "sha256 of its tarball; with none given, any existing bottle block is removed",
    )
    args = parser.parse_args(argv)
    if not args.asset:
        parser.error("at least one --asset is required")
    if args.bottle and not args.bottle_root_url:
        parser.error("--bottle needs --bottle-root-url")
    if args.bottle_root_url and not args.bottle:
        parser.error("--bottle-root-url needs at least one --bottle")
    for tag, sha256 in args.bottle:
        if not BOTTLE_TAG_RE.match(tag):
            parser.error(f"bottle tag {tag!r} is not a Homebrew tag symbol")
        if not SHA256_HEX_RE.match(sha256):
            parser.error(f"bottle sha256 for {tag!r} is not 64 lowercase hex digits: {sha256!r}")
    return args


def find_block(lines, start_re, what):
    """Return the (start, end) 0-based line-index range of `<what> do ... end`,
    inclusive, or None if the formula has no such block. `end` is matched at
    the same indentation as the opener, so nested `end`s (on_linux, etc.)
    don't terminate the search early.
    """
    for i, line in enumerate(lines):
        match = start_re.match(line)
        if not match:
            continue
        indent = match.group("indent")
        end_re = re.compile(r"^" + re.escape(indent) + r"end\s*$")
        for j in range(i + 1, len(lines)):
            if end_re.match(lines[j]):
                return (i, j)
        raise ValueError(f"line {i + 1}: '{what} do' has no matching 'end'")
    return None


def find_head_block(lines):
    return find_block(lines, HEAD_START_RE, "head")


def rewrite_version(lines, new_version):
    matches = [i for i, line in enumerate(lines) if VERSION_RE.match(line)]
    if len(matches) != 1:
        raise ValueError(f"expected exactly one 'version \"...\"' line, found {len(matches)}")
    i = matches[0]
    indent = VERSION_RE.match(lines[i]).group("indent")
    old_value = VERSION_RE.match(lines[i]).group("value")
    lines[i] = f'{indent}version "{new_version}"\n'
    return old_value, i


def rewrite_asset(lines, suffix, new_url, new_sha256, head_range):
    """Replace every `url "...<suffix>"` line (and the sha256 line right
    after each one) with the new url/sha256. Returns the number of
    occurrences rewritten.
    """
    targets = []
    for i, line in enumerate(lines):
        match = URL_RE.match(line)
        if not match or not match.group("value").endswith(suffix):
            continue
        targets.append(i)

    if not targets:
        raise ValueError(f"no 'url \"...{suffix}\"' line found")

    for i in targets:
        if head_range and head_range[0] <= i <= head_range[1]:
            raise ValueError(f"line {i + 1}: refusing to rewrite a url inside the head block")
        sha_i = i + 1
        if sha_i >= len(lines) or not SHA256_RE.match(lines[sha_i]):
            raise ValueError(f"line {i + 1}: 'url \"...{suffix}\"' is not followed by a sha256 line")
        url_indent = URL_RE.match(lines[i]).group("indent")
        sha_indent = SHA256_RE.match(lines[sha_i]).group("indent")
        lines[i] = f'{url_indent}url "{new_url}"\n'
        lines[sha_i] = f'{sha_indent}sha256 "{new_sha256}"\n'

    return len(targets)


def remove_bottle_block(lines):
    """Delete an existing `bottle do ... end` block together with the
    generated comment directly above it and the blank line that separated
    the block from what follows. Returns True if a block was removed.
    """
    block = find_block(lines, BOTTLE_START_RE, "bottle")
    if block is None:
        return False
    start, end = block
    indent = BOTTLE_START_RE.match(lines[start]).group("indent")
    first = start
    while first > 0:
        match = COMMENT_RE.match(lines[first - 1])
        if not match or match.group("indent") != indent:
            break
        first -= 1
    # The block sits between two blank lines; drop the one after it so the
    # neighbours are not left with a double blank.
    last = end
    if last + 1 < len(lines) and lines[last + 1].strip() == "" and first > 0 and lines[first - 1].strip() == "":
        last += 1
    del lines[first : last + 1]
    return True


def bottle_block_lines(root_url, bottles, indent):
    body = [f"{indent}{c}\n" for c in BOTTLE_COMMENT]
    body.append(f"{indent}bottle do\n")
    body.append(f'{indent}  root_url "{root_url}"\n')
    # Digests column-aligned on the longest tag, as `brew style`'s
    # BottleDigestIndentation cop requires.
    width = max(len(tag) for tag, _ in bottles)
    for tag, sha256 in bottles:
        pad = " " * (width - len(tag))
        body.append(f'{indent}  sha256 cellar: :any_skip_relocation, {tag}:{pad} "{sha256}"\n')
    body.append(f"{indent}end\n")
    return body


def rewrite_bottles(lines, root_url, bottles):
    """Make the formula's bottle block match `bottles`: remove the existing
    block, then, if there is anything to pin, write a fresh one after the
    license line (or the version line when there is none), which is where
    `brew style`'s ComponentsOrder cop wants it: after the stable pins,
    before `head do`. Returns a one-word description of what happened.
    """
    removed = remove_bottle_block(lines)
    if not bottles:
        return "removed" if removed else "absent"

    anchor = None
    for pattern, what in ((LICENSE_RE, "license"), (VERSION_RE, "version")):
        hits = [i for i, line in enumerate(lines) if pattern.match(line)]
        if len(hits) == 1:
            anchor = hits[0]
            indent = pattern.match(lines[anchor]).group("indent")
            break
    if anchor is None:
        raise ValueError("no single 'license' or 'version' line to put the bottle block after")

    block = ["\n"] + bottle_block_lines(root_url, bottles, indent)
    # Keep exactly one blank line between the new block and whatever follows.
    following = anchor + 1
    if following >= len(lines) or lines[following].strip() != "":
        block.append("\n")
    lines[anchor + 1 : anchor + 1] = block
    return "replaced" if removed else "inserted"


def main(argv):
    args = parse_args(argv)

    with open(args.formula, encoding="utf-8") as f:
        lines = f.readlines()

    head_range = find_head_block(lines)

    old_version, version_line = rewrite_version(lines, args.version)
    print(f"version: {old_version!r} -> {args.version!r} (line {version_line + 1})")

    for suffix, url, sha256 in args.asset:
        count = rewrite_asset(lines, suffix, url, sha256, head_range)
        plural = "occurrence" if count == 1 else "occurrences"
        print(f"...{suffix}: {count} {plural} repinned -> {url}")

    outcome = rewrite_bottles(lines, args.bottle_root_url, [tuple(b) for b in args.bottle])
    if args.bottle:
        tags = ", ".join(tag for tag, _ in args.bottle)
        print(f"bottle block: {outcome} ({tags}) -> {args.bottle_root_url}")
    else:
        print(f"bottle block: {outcome} (release publishes no bottles)")

    with open(args.formula, "w", encoding="utf-8") as f:
        f.writelines(lines)

    return 0


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv[1:]))
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        sys.exit(1)
